<?php
/**
 * Ultimate Management Engine - Professional Installer
 * Created by DarkScorpion
 * Features: Requirements check, Triple-DB setup (account, game, misc), Configuration generation.
 */

session_start();

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Requirements Check
$requirements = [
    'PHP Version >= 7.4' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO Extension'      => extension_loaded('pdo'),
    'PDO MySQL'          => extension_loaded('pdo_mysql'),
    'Config Writable'    => is_writable('../include/') || is_writable('../include/db_config.php')
];

$all_ok = !in_array(false, $requirements);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $db_host = $_POST['db_host'];
    $db_user = $_POST['db_user'];
    $db_pass = $_POST['db_pass'];
    
    // Triple databases
    $databases = ['db_account', 'db_game', 'db_misc'];

    try {
        $dsn = "mysql:host=$db_host";
        $pdo = new PDO($dsn, $db_user, $db_pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        foreach ($databases as $db_name) {
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8 COLLATE utf8_general_ci");
        }

        // Import SQL (Optional: only if setup.sql exists)
        $sql_file = 'setup.sql';
        if (file_exists($sql_file)) {
            $pdo->exec("USE `db_account` ");
            $sql = file_get_contents($sql_file);
            // Basic split by semicolon - simplified for speed
            $queries = array_filter(array_map('trim', explode(';', $sql)));
            foreach ($queries as $query) {
                if (!empty($query)) {
                    $pdo->exec($query);
                }
            }
            $success = "Databases initialized and schema imported!";
        } else {
            $success = "Triple-database stack initialized!";
        }

        if (empty($error)) {
            // Generate Config (New Path: include/db_config.php)
            $config_path = '../include/db_config.php';
            $config_content = "<?php
/**
 * Auto-Generated Database Configuration
 * Generated by Ultimate Management Engine Installer
 */

\$db_config = [
    'host' => '$db_host',
    'user' => '$db_user',
    'pass' => '$db_pass',
    'db_account' => 'db_account',
    'db_game'    => 'db_game',
    'db_misc'    => 'db_misc'
];

function GetDatabaseConnection(\$useDb = 'db_account') {
    global \$db_config;
    try {
        \$dsn = \"mysql:host={\$db_config['host']};dbname=\$useDb;charset=utf8\";
        \$pdo = new PDO(\$dsn, \$db_config['user'], \$db_config['pass']);
        \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        \$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
        return \$pdo;
    } catch (PDOException \$e) {
        die(\"Database Connection Error: \" . \$e->getMessage());
    }
}
?>";
            if (!is_dir('../include')) mkdir('../include', 0777, true);
            file_put_contents($config_path, $config_content);
            $step = 3;
        }

    } catch (PDOException $e) {
        $error = "Connection failed: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ultimate Engine Installer | DarkScorpion</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        :root {
            --primary: #fcc419;
            --primary-glow: rgba(252, 196, 25, 0.3);
            --bg: #0b0e14;
            --glass: rgba(255, 255, 255, 0.03);
            --glass-border: rgba(255, 255, 255, 0.08);
            --text: #ffffff;
            --text-muted: rgba(255, 255, 255, 0.4);
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'Inter', sans-serif;
            background: var(--bg);
            color: var(--text);
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            overflow-x: hidden;
            background-image: 
                radial-gradient(circle at 20% 20%, rgba(252, 196, 25, 0.05) 0%, transparent 40%),
                radial-gradient(circle at 80% 80%, rgba(44, 164, 191, 0.05) 0%, transparent 40%);
        }

        .installer-card {
            background: var(--glass);
            backdrop-filter: blur(20px);
            border: 1px solid var(--glass-border);
            border-radius: 24px;
            padding: 50px;
            width: 100%;
            max-width: 550px;
            box-shadow: 0 40px 100px rgba(0,0,0,0.5);
            position: relative;
            animation: fadeIn 0.8s ease-out;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .header { text-align: center; margin-bottom: 40px; }
        .badge {
            background: linear-gradient(135deg, #fcc419 0%, #ff922b 100%);
            color: #000;
            padding: 6px 16px;
            border-radius: 100px;
            font-weight: 800;
            font-size: 0.75rem;
            text-transform: uppercase;
            display: inline-block;
            margin-bottom: 15px;
            box-shadow: 0 4px 15px var(--primary-glow);
        }

        h1 { font-weight: 800; font-size: 1.8rem; letter-spacing: -0.5px; margin-bottom: 10px; }
        .subtitle { color: var(--text-muted); font-size: 0.95rem; }

        .requirement-list { margin-bottom: 30px; }
        .requirement-item {
            background: rgba(255,255,255,0.02);
            border: 1px solid var(--glass-border);
            padding: 15px 20px;
            border-radius: 12px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
            transition: 0.3s;
        }
        .requirement-item:hover { background: rgba(255,255,255,0.05); }
        .status-ok { color: #4ade80; font-weight: 600; }
        .status-fail { color: #f87171; font-weight: 600; }

        .input-group { margin-bottom: 20px; }
        label { display: block; margin-bottom: 8px; font-size: 0.85rem; color: var(--text-muted); font-weight: 600; }
        input {
            width: 100%;
            background: rgba(0,0,0,0.2);
            border: 1px solid var(--glass-border);
            padding: 14px 18px;
            border-radius: 12px;
            color: #fff;
            font-size: 0.95rem;
            transition: 0.3s;
        }
        input:focus { outline: none; border-color: var(--primary); box-shadow: 0 0 0 4px var(--primary-glow); }

        .btn-primary {
            width: 100%;
            background: linear-gradient(135deg, #fcc419 0%, #ff922b 100%);
            color: #000;
            border: none;
            padding: 16px;
            border-radius: 12px;
            font-weight: 800;
            font-size: 0.95rem;
            text-transform: uppercase;
            cursor: pointer;
            transition: 0.3s;
            box-shadow: 0 10px 25px var(--primary-glow);
        }
        .btn-primary:hover { transform: translateY(-2px); filter: brightness(1.1); box-shadow: 0 15px 30px var(--primary-glow); }
        .btn-primary:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }

        .alert {
            padding: 15px;
            border-radius: 12px;
            margin-bottom: 25px;
            font-size: 0.9rem;
            display: flex;
            align-items: center;
            gap: 12px;
        }
        .alert-error { background: rgba(248, 113, 113, 0.1); border: 1px solid #f87171; color: #f87171; }
        .alert-success { background: rgba(74, 222, 128, 0.1); border: 1px solid #4ade80; color: #4ade80; }

        .footer { text-align: center; margin-top: 30px; font-size: 0.8rem; color: var(--text-muted); }
        .footer a { color: var(--primary); text-decoration: none; font-weight: 600; }
    </style>
</head>
<body>

<div class="installer-card">
    <div class="header">
        <span class="badge">Prepare for Battle</span>
        <h1>Ultimate Engine</h1>
        <p class="subtitle">Management System Installer v2.0</p>
    </div>

    <?php if ($error): ?>
        <div class="alert alert-error"><i class="fas fa-exclamation-circle"></i> <?php echo $error; ?></div>
    <?php endif; ?>

    <?php if ($step === 1): ?>
        <div class="requirement-list">
            <?php foreach ($requirements as $name => $ok): ?>
                <div class="requirement-item">
                    <span><?php echo $name; ?></span>
                    <span class="<?php echo $ok ? 'status-ok' : 'status-fail'; ?>">
                        <i class="fas <?php echo $ok ? 'fa-check-circle' : 'fa-times-circle'; ?>"></i>
                        <?php echo $ok ? 'Ready' : 'Missing'; ?>
                    </span>
                </div>
            <?php endforeach; ?>
        </div>
        <button class="btn-primary" onclick="window.location.href='?step=2'" <?php echo !$all_ok ? 'disabled' : ''; ?>>
            Begin Initialization <i class="fas fa-arrow-right"></i>
        </button>

    <?php elseif ($step === 2): ?>
        <form method="POST">
            <div class="input-group">
                <label>Database Host</label>
                <input type="text" name="db_host" placeholder="e.g. localhost or db" value="db" required>
            </div>
            <div class="input-group">
                <label>Database User</label>
                <input type="text" name="db_user" placeholder="e.g. root" value="root" required>
            </div>
            <div class="input-group">
                <label>Database Password</label>
                <input type="password" name="db_pass" placeholder="Enter password or leave blank">
            </div>
            <p style="font-size: 0.8rem; color: var(--text-muted); margin-bottom: 25px; text-align: center;">
                <i class="fas fa-database"></i> This will set up: <b>db_account, db_game, and db_misc</b>.
            </p>
            <button type="submit" class="btn-primary">Ignite the Forge <i class="fas fa-fire"></i></button>
        </form>

    <?php elseif ($step === 3): ?>
        <div class="alert alert-success"><i class="fas fa-check-circle"></i> Installation successful!</div>
        <div style="text-align: center; margin-bottom: 30px;">
            <p style="margin-bottom: 15px;">The triple-database stack is now active and the config is generated.</p>
            <p style="color: var(--primary); font-weight: 800; font-size: 0.8rem; text-transform: uppercase;">Security Note: Please delete the /install folder now.</p>
        </div>
        <button class="btn-primary" onclick="window.location.href='../'">Enter the World <i class="fas fa-sign-in-alt"></i></button>
    <?php endif; ?>

    <div class="footer">
        Created by <a href="http://fb.me/darkscorpiont" target="_blank">DarkScorpion</a>
    </div>
</div>

</body>
</html>

